api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
	path('', views.index, name='index'),
	path('json/', views.get_json, name='get_json'),	
	path('text/image', views.image_text, name='image_text'),	
	path('text/audio', views.audio_text, name='audio_text'),	
] 

elirm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('vk/', include("vkapp.urls")),
    path('tools/', include("tools.urls")),
    path('', include("core.urls"))
]

tools/urls.py
from django.urls import path
from . import views


app_name = "tools"

urlpatterns = [
	path('', views.index, name='index'),
	path('convertor/audio', views.audio_convertor, name='audio_convertor'),
	path('convertor/image', views.image_convertor, name='image_convertor'),
	path('chat', views.chat, name='chat'),
    path('chat/<str:room_name>/', views.chat_room, name='chat_room'),
]

tools/models.py
from django.db import models


class Image(models.Model):    
	file = models.ImageField(upload_to='media/image_text')

	def __str__(self):
		return "Изображение"


class Audio(models.Model):    
	file = models.FileField(upload_to='media/audio_text')

	def __str__(self):
		return "Аудио"

tools/forms.py
from django import forms
from .models import *


class AudioForm(forms.ModelForm):
	class Meta:
		model = Audio
		fields = ['file']


class ImageForm(forms.ModelForm):
	class Meta:
		model = Image
		fields = ['file']

tools/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import AudioForm, ImageForm
import speech_recognition as sr
from pydub import AudioSegment
from PIL import Image
import pytesseract

# Create your views here.
def index(request):
    return render(request, "tools/index.html")


def audio_convertor(request):
    lang = "ru"
    if request.method == "POST":
        form = AudioForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            print(dir(cd['file']))
            name, _ = str(cd['file']).split(".")

        if "ogg" in cd['file'].content_type:
            audio = form.save()
            song = AudioSegment.from_ogg(audio.file)
            song.export(f"media/audio_text/{name}.wav", format="wav")
        elif "mp3" in cd['file'].content_type:
            audio = form.save()
            song = AudioSegment.from_mp3(audio.file)
            song.export(f"media/audio_text/{name}.wav", format="wav")
        elif "wav" in cd['file'].content_type:
        	pass
        else:
        	return render(request, "tools/audio_convertor.html", {"form": AudioForm()})

        r = sr.Recognizer()
        file = sr.AudioFile(f'media/audio_text/{name}.wav')
        with file as source:
            r.adjust_for_ambient_noise(source)
            audio = r.record(source)
            text = r.recognize_google(audio, language=lang)
            return HttpResponse(text)
    return render(request, "tools/audio_convertor.html", {"form": AudioForm()})


def image_convertor(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            image = form.save()
            image = Image.open(image.file)
            text = pytesseract.image_to_string(image, lang = "rus")
            return HttpResponse(text)
    return render(request, "tools/image_convertor.html", {"form": ImageForm()})


def chat(request):
    return render(request, "tools/chat.html")


def chat_room(request, room_name):
    return render(request, 'tools/chat_room.html', {
        'room_name': room_name
    })

templates/tools/audio_convertor.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <title>Tools list</title>
</head>
<body style="background-color: black;">


<form method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<input type="submit">
</form>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html> 
 

templates/tools/chat.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/tools/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

templates/tools/chat_room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/tools/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

templates/tools/image_convertor.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <title>Tools list</title>
</head>
<body style="background-color: black;">


<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.as_p}}
<input type="submit" name="">
</form>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html> 

templates/tools/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <title>Tools list</title>
</head>
<body style="background-color: black;">

<p><a href="{% url 'tools:audio_convertor' %}">1. Audio Convertor</a></p>
<p><a href="{% url 'tools:image_convertor' %}">2. Image Convertor</a></p>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html> 